### ISSUE TITLE
Support for local mongodb

### ISSUE THREAD

**Issue by vany0114** [Weapsy/Weapsy.CQRS#10]
Hi,

does it work for local mongodb, for example, to work in a development/local environment, or I must have a mongodb on azure with cosmosdb? I mean, for production I will use for sure cosmosdb, but I need a local mongodb for development.

Thanks!

**Comment by vany0114** [comment]
Nevermind bro! I already test it and works ok, BTW your Weapsy.CQRS is very cool!

**Comment by lucabriguglia** [comment]
Thanks @vany0114, glad you find it useful :-)
