### ISSUE TITLE
Issue in Extension method and about rebuilding state

### ISSUE THREAD

**Issue by chinookproject** [Weapsy/Weapsy.CQRS#9]
I'm playing around with this project in a console app. I found out that there is a small issue in `Weapsy.Cqrs.Extensions.ServiceCollectionExtensions`. You are not returning the instance of `IServiceCollection`.

So that should become:

```
        // changed void to IServiceCollection
        public static IServiceCollection AddWeapsyCqrs(this IServiceCollection services, params Type[] types)
        {
            // code here...
            return services; // You missed this one
        }
```

So far everything looks good. Only problem I have is a way to replay all the events from the EventStore, so I can rebuild the state of my read database. Because in the EventStore database all the DomainAggregate Types are saved like this:

```
Weapsy.Cqrs.Domain.IAggregateRoot, Weapsy.Cqrs, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null
```

Instead of the actual assemblyname of the domain class that implements the `AggregateRoot`. So somewhere there is an issue there as well.

Funny thing is that I don't have that last problem (with the wrong assembly name in the `DomainAggregate` table) when I download the source code and reference that directly in my project instead of using the Nuget package (using the `Weapsy.Cqrs.EventStore.EF.Sqlite` 2.1.0 version).

So it seems to be happening only in the Nuget package version.

**Comment by lucabriguglia** [comment]
Thank you so much for highlighting those issues!
I really don't know how I missed to return the service collection :-).
I'm going to fix it today.

Regarding the issue with the wrong saved type, I fixed it in the source code but I need to published a new NuGet package version.
I'll do it today as well.

**Comment by lucabriguglia** [comment]
Issues fixed and new packages published.
Please use version 2.1.2 for all packages.

**Comment by chinookproject** [comment]
Great, thanks for the fast update! All seems to be working in the new version.
